const CACHE_NAME = 'expense-tracker-v3';

// Files to cache immediately on install
const PRECACHE_URLS = [
  '/',
  '/index.html',
  '/manifest.json'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE_URLS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheName !== CACHE_NAME) {
            return caches.delete(cacheName);
          }
        })
      );
    }).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  // Skip non-http requests (like chrome-extension://)
  if (!event.request.url.startsWith('http')) return;

  event.respondWith(
    caches.match(event.request).then((cachedResponse) => {
      if (cachedResponse) {
        return cachedResponse;
      }

      return fetch(event.request).then((networkResponse) => {
        // Check if we received a valid response
        if (!networkResponse || networkResponse.status !== 200 || networkResponse.type !== 'basic') {
          return networkResponse;
        }

        // Cache JS, CSS, and Images dynamically as they are fetched
        // This handles the hashed filenames generated by Vite (e.g., assets/index-123.js)
        const responseToCache = networkResponse.clone();
        
        // Only cache static assets (JS, CSS, Images, Fonts)
        const url = event.request.url;
        if (url.match(/\.(js|css|png|jpg|jpeg|svg|json|woff2)$/) || url.endsWith('/')) {
             caches.open(CACHE_NAME).then((cache) => {
                cache.put(event.request, responseToCache);
             });
        }

        return networkResponse;
      });
    })
  );
});